modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
[[mods]]
modId="modulararmor"
version="${file.jarVersion}" #mandatory
displayName="Modular Armor" #mandatory
logoFile="modulararmor.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.modulararmor]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulararmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulararmor]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.22,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.modulararmor]]
    modId="curios"
    mandatory=true
    versionRange="[5.3.4,)"
    side="BOTH"
[[dependencies.modulararmor]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.20.1-81-FORGE,)"
    side="BOTH"

